version: '3'
services:
  go-url-shortener:
    restart: always
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - PORT=${PORT:-8080}
      - DATABASE_PATH=${DATABASE_PATH:-/opt/database.db}
    volumes:
      - ./db/database.db:/opt/database.db
    command:
      - /bin/sh
      - -c
      - |
        gourlshortener
      